config/routes.rb
Rails.application.routes.draw do
  mount MaintenanceTasks::Engine => "/maintenance_tasks"
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :labels
  
  get     'admin'  => 'users#index'
  get     'signup' => 'users#new'
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  
  root to: "tasks#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: "errors#internal_server_error", via: :all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :label_relations, dependent: :delete_all
  has_many :labels, through: :label_relations

  validates :title, :start, :endtime, :status, :priority, presence: true
  validate :endtime_is_greater, if: :dates_present?

  def dates_present?
    start.presence && endtime.presence
  end

  def endtime_is_greater
    if endtime < start
      errors.add :endtime, :endtime_is_greater, message: I18n.t('flash.task.end_start')
    end
  end

  def label_items
    labels.map(&:name)
  end

  def label_items=(names)
    self.labels = names.reject(&:empty?).map(&:strip).map{|item|
      Label.find_or_create_by(name: item)}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_task_user, only: [:show, :edit, :update, :destroy]
  before_action :find_record, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      @q = current_user.tasks.ransack(params[:q])
      @tasks = @q.result.includes(:labels, :label_relations)
      @tasks = @tasks.order(id: :ASC).page(params[:page]).per(9)
    else
      render :index
    end
  end
  

  def new
    @task = Task.new
  end


  def show
  end


  def create
    @task = current_user.tasks.create(task_params)

    if @task.save
      flash[:success] = t('flash.task.successful-create')
      redirect_to tasks_path
    else
      flash[:danger] = @task.errors.full_messages.to_sentence
      render :new
    end
  end


  def edit
  end


  def update
    if @task.update(task_params)
      flash[:success] = t('flash.task.successful-update')
      redirect_to tasks_path
    else
      flash[:danger] = @task.errors.full_messages.to_sentence
      render :edit
    end
  end


  def destroy
    @task.destroy if @task
    flash[:success] = t('flash.task.successful-delete')
    redirect_to tasks_path
  end
  

  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found
  

  private
  def task_params
    params.require(:task).permit(:title, :content, :start, :endtime, :priority, :status, {label_items: []} )
  end
  
  
  def handle_record_not_found
    flash[:danger] = t('flash.notfound')
    redirect_to :action => 'index'
  end


  def correct_task_user
    task = Task.find(params[:id])
    user = task.user
    if user != current_user && !current_user.admin?
      flash[:danger] = t('flash.user.nopermit')
      redirect_to(root_path)
    end  
  end


  def find_record
    @task = Task.includes(:labels, :label_relations).find(params[:id])
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<div class="panel p-5 w-75">
    <%= simple_form_for(task) do |f| %>
        <%= f.label t('show.title')%>
        <%= f.text_field :title, class: "form-control mb-4" %>

        <%= f.label t('show.content')%>
        <%= f.text_area :content, class: "form-control mb-4" %>

        <div class="d-flex mb-4">
            <div class="col-6">
            <%= f.label t('show.start')%>
            <%= f.text_field :start, as: :string, class: 'datepicker form-control' %>
            </div>

            <div class="col-6">
            <%= f.label t('show.end')%>
            <%= f.text_field :endtime, as: :string, class: 'datepicker form-control' %>
            </div>
        </div>

        <div class="row mb-3">
            <div class="d-flex col-6">
                <%= f.label :priority, t('show.priority-text'), class: "form-label" %>
                <div class="form-check">
                <%= f.radio_button :priority, 2, class: "form-check-label" %>
                <%= f.label t('show.priority')[2], class: 'badge priority-2'%>
                </div>
                <div class="form-check">
                <%= f.radio_button :priority, 1, class: "form-check-label" %>
                <%= f.label t('show.priority')[1], class: 'badge priority-1'%>
                </div>
                <div class="form-check">
                <%= f.radio_button :priority, 0, class: "form-check-label" %>
                <%= f.label t('show.priority')[0], class: 'badge priority-0'%>
                </div>
            </div>

            <div class="d-flex col-6">
                <%= f.label :status, t('show.status-text'), class: "form-label" %>
                <div class="form-check">
                <%= f.radio_button :status, 0, class: "form-check-label" %>
                <%= f.label t('show.status')[0], class: 'badge status-0' %>
                </div>
                <div class="form-check">
                <%= f.radio_button :status, 1, class: "form-check-label" %>
                <%= f.label t('show.status')[1], class: 'badge status-1' %>
                </div>
                <div class="form-check">
                <%= f.radio_button :status, 2, class: "form-check-label" %>
                <%= f.label t('show.status')[2], class: 'badge status-2' %>
                </div>
            </div>
        </div>

        <div class="mb-4" id='label-select'>
            <%= f.input :label_items,label: t('show.chooselabel'), as: :select, collection: Label.order(:name),
             label_method: :name,value_method: :name, input_html: {multiple: true} %>

        </div>

        <div class="d-flex justify-content-center"><%= f.submit class: 'btn btn-outline-secondary' %></div>
    <% end %>
</div>
<script>

</script>

app/views/tasks/_prevent_login.html.erb
<div class="d-flex flex-column text-center title" id="prevent-login">
  <h2 class="title">
  Please Log in to Manage Your Tasks
  </h2>
  <div><i class="fas fa-cloud-moon fa-4x mt-5"></i></div>
</div>

app/views/tasks/_tasklist.html.erb
  <table class="table table-hover">
    <thead>
      <tr>
        <td><%= t('show.title') %></td>
        <td class="text-center">
          <%= sort_link(@q, :created_at, t('show.created'), default_order: :ASC) %>
        </td>
        <td class="text-center">
          <%= sort_link(@q, :start, t('show.start'), default_order: :ASC) %>
        </td>
        <td class="text-center">
          <%= sort_link(@q, :endtime, t('show.end'), default_order: :DESC) %>
        </td>
        <td class="text-center">
          <%= sort_link(@q, :priority, t('show.priority-text'), default_order: :DESC) %>
        </td>
        <td class="text-center">
          <%= sort_link(@q, :status, t('show.status-text'), default_order: :ASC) %>
        </td>
        <td>
          <%= link_to t('show.label'), labels_path %>
          <%= link_to new_label_path do %><i class="fas fa-plus-circle"></i><%end%>
        </td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% if @tasks.length < 1 %>
        <tr><td class="text-center py-3 fs-5" colspan="7">No Any Tasks Yet</td></tr>
      <%else%>
        <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task_path(task) do%><%= task.title %></td><% end %>
          <td class="text-center time"><%= task.created_at.strftime("%m %d, %Y") %></td>
          <td class="text-center time"><%= task.start.strftime("%m %d, %Y") %></td>
          <td class="text-center time"><%= task.endtime.strftime("%m %d, %Y") %></td>
          <td class="text-center">
            <span class="badge priority-<%= task.priority %>"><%= t('show.priority')[task.priority] %></span>
          </td>
          <td class="text-center">
            <span class="badge status-<%= task.status %>"><%= t('show.status')[task.status] %></span>
          </td>
          <td class='d-flex flex-wrap'>
          <% task.labels.each do |label| %>
            <span class="badge me-2 label_colors<%= label.color %>">
              <%= label.name %>
            </span>
          <% end %>
          </td>
          <td>
            <%= link_to edit_task_path(task) do %>
              <i class="fas fa-pen "></i>
            <% end %>
            <%= link_to task_path(task), method: "delete", data: { confirm: "確認刪除" }, id: "delete-#{task.id}" do %>
              <i class="fas fa-trash-alt  ms-1"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/tasks/edit.html.erb
<div class="pb-5 d-flex flex-column align-items-center">

<h1 class="mb-3 title text-center">Edit Task</h1>

<%= render "form", task: @task%>  

<br />
<% if current_user.admin? && @task.user!=current_user %>
  <%= link_to t('user.admin-text.back-profile'), user_path(@task.user), class:"btn btn-primary mt-4"%>
<% else %>
  <%= link_to t('show.back'), tasks_path, class:"btn btn-primary mt-4"%>
<% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to root_path do %><h1 class="mb-3 text-center title">Task Manager</h1><% end %>
<% if logged_in? %>
<div class="d-flex align-items-center justify-content-between my-4">
    <%= link_to t('show.new'), new_task_path, class:"btn btn-outline-primary" %>
    <div>
      <%= search_form_for @q, class: 'd-flex align-items-center justify-content-center' do |f| %>
        <%= f.search_field :title_cont, class: 'input-outline-primary form-control w-25', placeholder: t('filter.title') %>

        <%= f.search_field :labels_name_cont, class: 'input-outline-primary form-control w-25 ms-3', placeholder: t('filter.label') %>

        <%= f.select :status_eq, options_for_select([["#{t('filter.status')}  ▾", '' ], [t('show.status')[0], 0], [t('show.status')[1], 1], [t('show.status')[2], 2]]), {}, { class: 'input-outline-primary form-control w-25 ms-3' } %>

        <%= f.submit "Search", name: 'search', class: 'btn btn-outline-primary ms-3' %>
      <% end %>
    </div>
  </div>

  <div class='p-2 mb-5 panel'>
  <%= render "tasklist", tasks: @tasks %>
  </div>

  <%= paginate @tasks, theme: 'twitter-bootstrap-4'%>
<% else %>
  <%= render "prevent_login" %>
<% end %>

app/views/tasks/new.html.erb
<div class="pb-5 d-flex flex-column align-items-center">

<h1 class="mb-3 title text-center">New Task</h1>

<%= render "form", task: @task %>  

<br />

<%= link_to t('show.back'), tasks_path, class:"btn btn-primary mt-4"%>

</div>

app/views/tasks/show.html.erb
<div class="pb-5 d-flex flex-column align-items-center">

  <h1 class="mb-3 title text-center fw-normal"><%= @task.title %></h1>
  <div class="panel p-5 w-75">
  <%= @task.user.name %>
  <%= @task.user.email %>

    <div class='row mt-3'><div class='col-2'><%= t('show.start') %></div><div class='col-10'><%= @task.start.strftime("%m %d, %Y") %></div></div>
    <div class='row mt-2'><div class='col-2'><%= t('show.end') %></div><div class='col-10'><%= @task.endtime.strftime("%m %d, %Y") %></div></div>


    <div class='mt-3 row'>
      <div class='col-2'><%= t('show.content') %></div><div class='col-10'><%= @task.content %></div>
    </div>


    <div class='row mt-3'><div class='col-2'>優先度</div><div class='col-10'><span class="badge priority-<%= @task.priority %>"><%= t('show.priority')[@task.priority] %></span></div></div>
    <div class='row mt-2'><div class='col-2'>狀態</div><div class='col-10'><span class="badge status-<%= @task.status %>"><%= t('show.status')[@task.status] %></span></div></div>

    <div class='row mt-2'>
      <div class='col-2'>標籤</div>
      <div class='col-10'>
        <% @task.labels.each do |label| %>
          <span class="badge me-2 label_colors<%= label.color %>">
            <%= label.name %>
          </span>
        <% end %>
      </div>
    </div>


  </div>
<% if current_user.admin? && @task.user!=current_user %>
  <%= link_to t('user.admin-text.back-profile'), user_path(@task.user), class:"btn btn-primary mt-4"%>
<% else %>
  <%= link_to t('show.back'), tasks_path, class:"btn btn-primary mt-4"%>
<% end %>
</div>