config/routes.rb
Rails.application.routes.draw do
  mount MaintenanceTasks::Engine => "/maintenance_tasks"
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :labels
  
  get     'admin'  => 'users#index'
  get     'signup' => 'users#new'
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  
  root to: "tasks#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: "errors#internal_server_error", via: :all
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :label_relations, dependent: :delete_all
  has_many :tasks, through: :label_relations

  attribute :color, :string, default: rand(7)
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :logged_in_user
  before_action :find_label, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :destroy]

  def index
    @labels = Label.includes(:tasks, :label_relations).page(params[:page]).per(9)
  end

  def show
    @label = Label.includes(:tasks, :label_relations).find(params[:id])
    @q = @label.tasks.where(user: current_user).ransack(params[:q])
    @tasks = @q.result.order('id ASC').page(params[:page]).per(9)
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      flash[:success] = t('flash.label.successful-create')
      redirect_to labels_path
    else
      flash[:danger] = @label.errors.full_messages.to_sentence
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      flash[:success] = t('flash.label.successful-update')
      redirect_to labels_path
    else
      flash[:danger] = @label.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @label.destroy if @label
    flash[:success] = t('flash.task.successful-delete')
    redirect_to labels_path
  end

  private
  def label_params
    params.require(:label).permit(:name, :color)
  end

  def find_label
    @label = Label.find(params[:id])
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<div class="panel p-4 w-50">
  <%= bootstrap_form_for(@label) do |f| %>
    <%= f.text_field :name, class: "form-control mb-4", label: t('label.name'), label_class: 'mb-2' %>

    <div class="mb-2"><%= t('label.choosecolor') %></div>
    <div class="d-flex flex-wrap">
      <div class="me-5">

        <%= f.radio_button :color,'1', label: 'Red', label_class:'badge label_colors1 mb-2' %>
        <%= f.radio_button :color,'2', label: 'Orange', label_class:'badge label_colors2 mb-2' %>
        <%= f.radio_button :color,'3', label: 'Green', label_class:'badge label_colors3 mb-2' %>
        <%= f.radio_button :color,'4', label: 'Blue', label_class:'badge label_colors4 mb-2' %>
        <%= f.radio_button :color,'5', label: 'Dark Blue', label_class:'badge label_colors5 mb-2' %>
        <%= f.radio_button :color,'6', label: 'Purple', label_class:'badge label_colors6 mb-2' %>
      </div>
    </div>

    <div class="d-flex justify-content-center mt-4"><%= f.submit class: 'btn btn-outline-secondary' %></div>
  <% end %>
</div>

app/views/labels/edit.html.erb
<div class="pb-5 d-flex flex-column align-items-center">

<h1 class="mb-3 title text-center">Edit Label</h1>

<%= render "form", label: @label %>

<br />

<%= link_to t('label.back'), labels_path, class:"btn btn-primary mt-4"%>

</div>

app/views/labels/index.html.erb
<h1 class="mb-3 text-center title">All Labels</h1>

<%= link_to t('label.new'), new_label_path, class:"btn btn-outline-primary mb-4" %>

<div class='p-2 mb-5 panel'>
  <table class="table table-hover">
    <thead>
      <tr>
        <td class="text-center"><%= t('label.name') %></td>
        <td class="text-center"><%= t('show.created') %>
        </td>
        <td class="text-center"><%= t('show.task_count') %>
        </td>
        <% if current_user.admin? %>
          <td></td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% if @labels.length < 1 %>
        <tr><td class="text-center py-3 fs-5" colspan="7">No Any labels Yet</td></tr>
      <%else%>
        <% @labels.each do |label| %>
        <tr>
          <td class="text-center"><%= link_to label_path(label) do%><%= label.name %></td><% end %>
          <td class="text-center time"><%= label.created_at.strftime("%m %d, %Y") %></td>
          <td class='text-center'>
            <%= label.tasks.where(user: current_user).count %>
          </td>

          <% if current_user.admin? %>
            <td class="text-center">
              <%= link_to edit_label_path(label) do %>
                <i class="fas fa-pen "></i>
              <% end %>
              <%= link_to label_path(label), method: "delete", data: { confirm: "確認刪除" }, id: "delete-#{label.id}" do %>
                <i class="fas fa-trash-alt  ms-1"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

</div>
<%= paginate @labels, theme: 'twitter-bootstrap-4'%>

app/views/labels/new.html.erb
<div class="pb-5 d-flex flex-column align-items-center">

<h1 class="mb-3 title text-center">New Label</h1>

<%= render "form", label: @label %>

<br />

<%= link_to t('label.back'), labels_path, class:"btn btn-primary mt-4"%>

</div>

app/views/labels/show.html.erb
<h1 class="mb-3 text-center title"><%= @label.name%></h1>

<div class='p-2 mb-4 panel'>
  <%= render 'tasks/tasklist', tasks: @tasks %>
</div>
<%= paginate @tasks, theme: 'twitter-bootstrap-4'%>

<div class="w-100 mb-5 d-flex justify-content-center align-items-center">
  <%= link_to t('show.back'), tasks_path, class:"btn btn-primary mt-4"%>
</div>