config/routes.rb
Rails.application.routes.draw do
  mount MaintenanceTasks::Engine => "/maintenance_tasks"
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :labels
  
  get     'admin'  => 'users#index'
  get     'signup' => 'users#new'
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  
  root to: "tasks#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: "errors#internal_server_error", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :delete_all

  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :tel, presence: true, length: {maximum: 10}

  has_secure_password
  validates :password, length: {minimum: 6}, allow_nil: true
  
  # Admin deletion settings
  scope :admin_count, -> { where(admin: true).count}
  before_save :validate_admin_update
  def validate_admin_update
    if self.admin_changed?(from: true, to: false) && User.admin_count == 1
      errors.add :admin, message: i18n.t('user.admin-text.oneleft')
      throw :abort
    end
  end

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest 
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: :destroy

  def index
    if !current_user.admin?
      flash[:danger] = t('flash.user.nopermit')
      redirect_to user_path(session[:user_id])
    end
    @users = User.includes(:tasks).order('id ASC').page(params[:page]).per(9)
  end

  def show
    if not session[:user_id]
      redirect_to root_path
    end
    @user = User.find(params[:id])
    if current_user.admin?
      @q = User.find(params[:id]).tasks.ransack(params[:q])
      @tasks = @q.result
      @tasks = @tasks.order('id ASC').page(params[:page]).per(9)
    end
  end


  def new
    if session[:user_id] && !current_user.admin?
      redirect_to user_path(session[:user_id])
    end
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t('flash.task.welcome')
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  def edit
  end


  def update
    if current_user.admin?
      if @user.update(admin_params)
        flash[:success] = t('flash.user.successful-update')
        redirect_to admin_path
      else
        flash[:danger] = @user.errors.full_messages.to_sentence
        render :edit
      end
    else
      if @user.update(user_params)
        flash[:success] = t('flash.user.successful-update')
        redirect_to @user
      else
        render :edit
      end
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t('flash.user.successful-delete')
    redirect_to admin_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :tel, :password, :password_confirmation)
  end

  def admin_params
    params.require(:user).permit(:name, :email, :tel, :password, :password_confirmation, :admin)
  end
  
  
  def handle_record_not_found
    flash[:notice] = t('flash.notfound')
    redirect_to :action => 'index'
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for(:title, "Update Profile") %>
<div class="d-flex flex-column justify-content-center align-items-center">
<h1 class="mb-3 title text-center">
  <% if current_user.id == @user.id %>
    Update Your Profile
  <% else %>
    Update User Profile
  <% end %>
</h1>

<div class="panel p-4 w-50">

<%= bootstrap_form_with(model: @user, local: true) do |f| %>
  <h4><%= t('user.basic-settings') %></h4>
  <div class='mb-3'><%= f.text_field :name, label: t('user.name') %></div>

  <div class='mb-3'><%= f.email_field :email, label: '' %></div>

  <div class='mb-3'><%= f.text_field :tel, label: t('user.tel') %></div>

  <% if current_user.id == @user.id %>
    <h4 class='mt-4'><%= t('user.set-password') %></h4>
    <div class='mb-3'><%= f.password_field :password, label: t('user.password') %></div>
    <div><%= f.password_field :password_confirmation, label: t('user.password-confirmation') %></div>
  <% end %>
  <% if current_user.admin? %>
    <div class="mt-4"><%= t('user.admin-text.settings') %></div>
    <% if @user.admin? %>
      <% if !current_user?(@user) %>
        <div class="mt-2"><%= t('user.admin-text.is') %></div>
        <div><%= f.radio_button :admin, 0, label: t('user.admin-text.remove') %></div>
      <% else %>
        <div class="mt-2"><%= f.radio_button :admin, 0, label: t('user.admin-text.out') %></div>
      <% end %>
    <% else %>
      <div class="mt-2"><%= f.radio_button :admin, 1, label: t('user.admin-text.add') %></div>
    <% end %>


  <% end %>

  <div class="d-flex justify-content-center mt-4"><%= f.submit t('user.save-changes'), class: 'btn btn-outline-secondary' %></div>

<% end %>

</div>
<% if current_user.admin?%>
  <%= link_to t('user.back-admin'), admin_path, class:"btn btn-primary mt-5"%>
<% end %>
</div>

app/views/users/index.html.erb
<h1 class="mb-3 text-center title">All Users</h1>

<%= link_to t('user.new'), new_user_path, class:"btn btn-outline-primary mb-4" %>

<div class='p-2 mb-5 panel'>
  <table class="table table-hover">
    <thead>
      <tr>
        <td><%= t('user.name') %></td>
        <td class="text-center">
          Email
        </td>
        <td class='text-center'><%= t('show.task_count') %></td>
        <td></td>
      </tr>
    </thead>
  <% @users.each do |user| %>
    <tr class=''>
      <td><%= link_to user.name, user%><% if user.admin? %><span class="badge status-2 ms-3"><%= t('user.admin') %></span><% end %></td>
      <td><%= user.email %></td>
      <td class='text-center'><%= user.tasks.count %></td>
      <td class='text-center'>
          <%= link_to edit_user_path(user) do %>
            <i class="fas fa-pen "></i>
          <% end %>
         <% if !current_user?(user) %>
          <%= link_to user, method: :delete ,data: {confirm: "You sure?"} do%>
            <i class="fas fa-trash-alt ms-3"></i>
          <% end %>
         <% else %>
             <i class="fas fa-trash-alt ms-3 text-white-50"></i>
         <% end %>
      </td>
    </tr>
  <% end %>
  </table>
</div>
<%= paginate @users, theme: 'twitter-bootstrap-4'%>

app/views/users/new.html.erb
<% content_for(:title, "Sign up") %>
<div class="d-flex flex-column justify-content-center align-items-center">
<h1 class="mb-3 title text-center">
<% if !current_user %>
  Sign up
  <% submit_text = 'Create My Account' %>
<% else %>
  Create New User
  <% submit_text = 'Create' %>
<% end %>
</h1>

<div class="panel p-4 w-50">

<%= bootstrap_form_with(model: @user, local: true) do |f| %>

  <div class='mb-3'><%= f.text_field :name %></div>

  <div class='mb-3'><%= f.email_field :email %></div>

  <div class='mb-3'><%= f.text_field :tel %></div>

  <div class='mb-3'><%= f.password_field :password %></div>

  <div class='mb-4'><%= f.password_field :password_confirmation %></div>

  <div class="d-flex justify-content-center"><%= f.submit "#{submit_text}", class: 'btn btn-outline-secondary' %></div>

<% end %>

</div>
<% if current_user %>
  <%= link_to t('user.back-admin'), admin_path, class:"btn btn-primary mt-5"%>
<% end %>
</div>

app/views/users/show.html.erb
<% content_for(:title, "Profile Page") %>

<h1 class="mb-3 text-center title">User Profile</h1>
<% if current_user.admin? %>
  <div class='p-4 mb-5 panel'>
    <h5><%= t('user.basicinfo') %></h5>
    <div class='row'>
      <div class="col-4 d-flex">
        <div class="me-3"><%= t('user.name') %></div>
        <div>
          <%= @user.name %>
          <% if @user.admin? %>
            <span class="badge status-2 ms-3"><%= t('user.admin') %></span>
          <% end %>
        </div>
      </div>
      <div class="col-4 d-flex">
        <div class="me-3">Email</div>
        <div><%= @user.email %></div>
      </div>
      <div class="col-4 d-flex">
        <div class="me-3"><%= t('user.create') %></div>
        <div><%= @user.created_at.strftime("%m %d, %Y") %></div>
      </div>
    </div>

    <h5 class="mt-4"><%= t('user.tasklist') %></h5>

    <%= render "tasks/tasklist", tasks: @tasks %>

    <div class="w-100 d-flex justify-content-center align-items-center">
      <%= paginate @tasks, theme: 'twitter-bootstrap-4'%>
    </div>
  </div>
  <div class="w-100 d-flex justify-content-center align-items-center">
    <%= link_to t('user.back-admin'), admin_path, class:"btn btn-primary"%>
  </div>

<% else %>
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class='p-4 mb-5 panel w-50'>
      <h5 class='text-center mb-3'><%= t('user.basicinfo') %></h5>
        <div class="d-flex mb-3">
          <div class="me-3 col-3"><%= t('user.name') %></div>
          <div class="col-9">
            <%= @user.name %>
            <% if @user.admin? %>
              <span class="badge status-2 ms-3"><%= t('user.admin') %></span>
            <% end %>
          </div>
        </div>
        <div class="d-flex mb-3">
          <div class="me-3 col-3">Email</div>
          <div class="col-9"><%= @user.email %></div>
        </div>
        <div class="d-flex mb-3">
          <div class="me-3 col-3"><%= t('user.create') %></div>
          <div class="col-9"><%= @user.created_at.strftime("%m %d, %Y") %></div>
        </div>
    </div>
  </div>
<% end %>