config/routes.rb
Rails.application.routes.draw do
  mount MaintenanceTasks::Engine => "/maintenance_tasks"
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :labels
  
  get     'admin'  => 'users#index'
  get     'signup' => 'users#new'
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  
  root to: "tasks#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: "errors#internal_server_error", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %>
      <title><%= "#{content_for(:title)} | Task Manager Ruby" %></title>
    <% else %>
      <title>Task Manager Ruby</title>
    <% end %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.svg') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3642c0e780.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="px-5 navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><i class="fas fa-cloud-moon me-2"></i>Task Manager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to 'Task List',root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Label List',labels_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Profile", current_user, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Settings", edit_user_path(current_user), class: 'nav-link' %>
              </li>
              <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to "Admin Page", admin_path, class: 'nav-link' %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "Log out", logout_path, method: "delete", id: 'logout', class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: 'nav-link' %>
              </li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class='container pt-5'>
      <div class='d-flex flex-column justify-content-center align-items-center'>
        <% flash.each do |message_type, message| %>
          <div class='alert alert-<%= message_type %>'><%= message %></div>
        <% end %>
      </div>

      <%= yield %>
      <% # debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>